import type { Metadata } from "next";
import { Cute_Font } from "next/font/google";
import "./globals.css";

const cuteFont = Cute_Font({
  variable: "--font-cute",
  subsets: ["latin"],
  weight: "400"
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cuteFont.variable} antialiased`}
      >
        <div className={"z-0 fixed left-0 top-0 right-0 h-12 bg-primary-200"}>
        </div>
        <div className={"z-10 absolute inset-0 p-14 overflow-y-scroll lg:px-48 xl:px-96"}>
          {children}
        </div>
        <div className={"z-0 fixed left-0 bottom-0 right-0 h-12 bg-primary-200"}>
        </div>
      </body>
    </html>
  );
}
